export const VIEW_DETAILS = "VIEW_DETAILS";
export const CLOSE_DETAILS = "CLOSE_DETAILS";

export const VIEW_PRODUCT_DETAILS = "VIEW_PRODUCT_DETAILS";
export const CLOSE_PRODUCT_DETAILS = "CLOSE_PRODUCT_DETAILS";

export const ADD_PRODUCT_IN_CART = "ADD_PRODUCT_IN_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";

export const ADD_PRODUCT_IN_WISHLIST = "ADD_PRODUCT_IN_WISHLIST";
export const REMOVE_PRODUCT_FROM_WISHLIST = "REMOVE_PRODUCT_FROM_WISHLIST";

export const SET_DATA = "SET_DATA";

export const ADD_DATA_IN_CART_ARRAY = "ADD_DATA_IN_CART_ARRAY";
export const REMOVE_DATA_FROM_CART_ARRAY = "REMOVE_DATA_FROM_CART_ARRAY";
export const ADD_DATA_IN_WISHLIST_ARRAY = "ADD_DATA_IN_WISHLIST_ARRAY";
export const REMOVE_DATA_FROM_WISHLIST_ARRAY = "REMOVE_DATA_FROM_WISHLIST_ARRAY";