export const VIEW_DETAILS = "VIEW_DETAILS";
export const CLOSE_DETAILS = "CLOSE_DETAILS";

export const VIEW_PRODUCT_DETAILS = "VIEW_PRODUCT_DETAILS";
export const CLOSE_PRODUCT_DETAILS = "CLOSE_PRODUCT_DETAILS";

export const ADD_PRODUCT_IN_CART = "ADD_PRODUCT_IN_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";

export const ADD_PRODUCT_IN_WISHLIST = "ADD_PRODUCT_IN_WISHLIST";
export const REMOVE_PRODUCT_FROM_WISHLIST = "REMOVE_PRODUCT_FROM_WISHLIST";

